CREATE OR REPLACE TABLE `{{ params.dwh_dataset }}.D_TIME` AS
SELECT DISTINCT
  ARRIVAL_DATE DATE,
  EXTRACT(DAY FROM ARRIVAL_DATE) DAY,
  EXTRACT(MONTH FROM ARRIVAL_DATE) MONTH,
  EXTRACT(YEAR FROM ARRIVAL_DATE) YEAR,
  EXTRACT(QUARTER FROM ARRIVAL_DATE) QUARTER,
  EXTRACT(DAYOFWEEK FROM ARRIVAL_DATE) DAYOFWEEK,
  EXTRACT(ISOWEEK FROM ARRIVAL_DATE) WEEKOFYEAR

FROM
  `{{ params.project_id }}.{{ params.dwh_dataset }}.F_IMMIGRATION_DATA`
